[package]
name = "gb-emulator"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0"
gb_core = {path = "core"}

[workspace]
members = ["core"]

[workspace.package]
version = "0.1.0"
edition = "2024"
